import '../models/models.dart';

class MockData {
  // ============== BANNERS ==============
  static List<Banner> banners = [
    Banner(
      bannerId: 'b1',
      titleEn: 'Welcome to Appski',
      titleMk: 'Добредојдовте во Appski',
      imageUrl: 'https://images.unsplash.com/photo-1580408384706-b1cb8bab1127?w=800',
      linkType: 'none',
    ),
    Banner(
      bannerId: 'b2',
      titleEn: 'Macedonian Heritage Festival 2026',
      titleMk: 'Македонски Фестивал на Наследство 2026',
      imageUrl: 'https://images.unsplash.com/photo-1533174072545-7a4b6ad7a6c3?w=800',
      linkType: 'event',
      linkId: 'e1',
    ),
    Banner(
      bannerId: 'b3',
      titleEn: 'Discover Macedonian Businesses',
      titleMk: 'Откријте Македонски Бизниси',
      imageUrl: 'https://images.unsplash.com/photo-1556761175-4b46a572b786?w=800',
      linkType: 'url',
      externalUrl: 'https://macedoniancommunity.org.au',
    ),
  ];

  // ============== NEWS ==============
  static List<NewsArticle> news = [
    NewsArticle(
      newsId: 'n1',
      titleEn: 'Macedonian Community Celebrates 50th Anniversary in Melbourne',
      titleMk: 'Македонската заедница прославува 50 години во Мелбурн',
      bodyEn: 'The Macedonian Community of Australia Inc. celebrated its 50th anniversary with a grand gala event held at the Melbourne Convention Centre. Over 2,000 community members attended the event, which featured traditional music, dance performances, and speeches from community leaders and government officials.\n\nThe evening showcased the rich cultural heritage of the Macedonian diaspora in Australia, highlighting decades of contributions to Australian multicultural society. Traditional folk ensembles performed oro dances, while renowned musicians played classic Macedonian songs that had the audience singing along.\n\n"This milestone represents not just 50 years of organization, but 50 years of preserving our identity, language, and traditions in our adopted homeland," said the community president in his opening address.',
      bodyMk: 'Македонската заедница на Австралија прославува 50 години со голем гала настан одржан во Конвенцискиот центар во Мелбурн. Над 2.000 членови на заедницата присуствуваа на настанот, кој вклучуваше традиционална музика, танцови претстави и говори од лидери на заедницата и владини функционери.\n\nВечерта го покажа богатото културно наследство на македонската дијаспора во Австралија.',
      category: 'Community',
      publishedAt: DateTime(2026, 3, 25),
      featuredImage: 'https://images.unsplash.com/photo-1540575467063-178a50c2df87?w=800',
      author: 'MCA Editorial',
      readingTime: 5,
    ),
    NewsArticle(
      newsId: 'n2',
      titleEn: 'New Macedonian Language Classes Starting in Sydney',
      titleMk: 'Нови часови по македонски јазик почнуваат во Сиднеј',
      bodyEn: 'Macedonian language classes for children and adults will begin next month at the community center in Sydney. The program aims to preserve the Macedonian language among younger generations. Classes will be offered at beginner, intermediate, and advanced levels.\n\nRegistrations are now open for all age groups. Children aged 5-12 will have Saturday morning classes, while teenagers and adults can choose from evening sessions during the week.',
      bodyMk: 'Часови по македонски јазик за деца и возрасни ќе почнат следниот месец во центарот на заедницата во Сиднеј. Програмата има за цел да го зачува македонскиот јазик меѓу помладите генерации.',
      category: 'Community',
      publishedAt: DateTime(2026, 3, 22),
      featuredImage: 'https://images.unsplash.com/photo-1503676260728-1c00da094a0b?w=800',
      readingTime: 3,
    ),
    NewsArticle(
      newsId: 'n3',
      titleEn: 'Australian-Macedonian Footballer Signs with A-League Club',
      titleMk: 'Австралиско-македонски фудбалер потпиша со А-Лига клуб',
      bodyEn: 'A talented young Australian-Macedonian footballer has signed a professional contract with Melbourne Victory in the A-League. The 19-year-old midfielder, who grew up playing for the local Macedonian community football club, will join the first team squad for the upcoming season.\n\nThe signing represents a proud moment for the Macedonian community in Australia, with many hoping it will inspire more young players from the community.',
      bodyMk: 'Талентиран млад австралиско-македонски фудбалер потпиша професионален договор со Мелбурн Виктори во А-Лигата.',
      category: 'Sports',
      publishedAt: DateTime(2026, 3, 20),
      featuredImage: 'https://images.unsplash.com/photo-1431324155629-1a6deb1dec8d?w=800',
      readingTime: 4,
    ),
    NewsArticle(
      newsId: 'n4',
      titleEn: 'Traditional Macedonian Cuisine Takes Center Stage at Food Festival',
      titleMk: 'Традиционалната македонска кујна во центарот на фестивал за храна',
      bodyEn: 'Macedonian food lovers united at the annual multicultural food festival in Brisbane, where traditional Macedonian cuisine was a highlight. Vendors served favorites including tavche gravche, ajvar, zelnik, and burek, alongside grilled meats and pastries.\n\nThe Macedonian stalls drew long queues throughout the weekend event, with many non-Macedonian Australians discovering the rich flavors for the first time.',
      bodyMk: 'Љубителите на македонска храна се обединија на годишниот мултикултурен фестивал за храна во Бризбејн.',
      category: 'Culture',
      publishedAt: DateTime(2026, 3, 18),
      featuredImage: 'https://images.unsplash.com/photo-1555939594-58d7cb561ad1?w=800',
      readingTime: 3,
    ),
    NewsArticle(
      newsId: 'n5',
      titleEn: 'Community Center Renovations Complete in Perth',
      titleMk: 'Реновирањето на центарот на заедницата во Перт е завршено',
      bodyEn: 'The Macedonian community center in Perth has undergone a major renovation, with modern facilities now available for events, meetings, and cultural activities. The upgraded center features a new performance hall, commercial kitchen, and multimedia room.',
      bodyMk: 'Центарот на македонската заедница во Перт помина низ голема реновација.',
      category: 'Community',
      publishedAt: DateTime(2026, 3, 15),
      featuredImage: 'https://images.unsplash.com/photo-1486406146926-c627a92ad1ab?w=800',
      readingTime: 2,
    ),
  ];

  // ============== BUSINESSES ==============
  static List<Business> businesses = [
    Business(
      businessId: 'bus1',
      nameEn: 'Balkan Grill House',
      nameMk: 'Балкан Грил Куќа',
      category: 'Restaurant',
      descriptionEn: 'Authentic Macedonian and Balkan cuisine in the heart of Melbourne. Specializing in grilled meats, traditional salads, and homemade breads.',
      descriptionMk: 'Автентична македонска и балканска кујна во срцето на Мелбурн.',
      address: '123 Smith Street',
      suburb: 'Collingwood',
      state: 'VIC',
      latitude: -37.8007,
      longitude: 144.9873,
      phone: '+61 3 9000 1111',
      email: 'info@balkangrill.com.au',
      website: 'https://balkangrill.com.au',
      imageUrl: 'https://images.unsplash.com/photo-1517248135467-4c7edcad34c4?w=800',
      rating: 4.7,
      reviewCount: 128,
    ),
    Business(
      businessId: 'bus2',
      nameEn: 'Macedonia Bakery',
      nameMk: 'Македонија Пекара',
      category: 'Bakery',
      descriptionEn: 'Traditional Macedonian pastries, bread, and sweets. Famous for our homemade burek and zelnik.',
      descriptionMk: 'Традиционални македонски пецива, леб и слатки.',
      address: '45 Victoria Road',
      suburb: 'Thomastown',
      state: 'VIC',
      latitude: -37.6830,
      longitude: 145.0148,
      phone: '+61 3 9000 2222',
      email: 'orders@macedoniabakery.com.au',
      website: 'https://macedoniabakery.com.au',
      imageUrl: 'https://images.unsplash.com/photo-1509440159596-0249088772ff?w=800',
      rating: 4.9,
      reviewCount: 256,
    ),
    Business(
      businessId: 'bus3',
      nameEn: 'Skopje Legal Services',
      nameMk: 'Скопје Правни Услуги',
      category: 'Professional',
      descriptionEn: 'Bilingual legal services specializing in immigration, property, and family law. Serving the Macedonian community for over 20 years.',
      descriptionMk: 'Двојазични правни услуги специјализирани за имиграција, имот и семејно право.',
      address: '200 Queen Street',
      suburb: 'Melbourne',
      state: 'VIC',
      phone: '+61 3 9000 3333',
      email: 'legal@skopjelegal.com.au',
      website: 'https://skopjelegal.com.au',
      imageUrl: 'https://images.unsplash.com/photo-1589829545856-d10d557cf95f?w=800',
      rating: 4.5,
      reviewCount: 42,
    ),
    Business(
      businessId: 'bus4',
      nameEn: 'Ohrid Travel Agency',
      nameMk: 'Охрид Туристичка Агенција',
      category: 'Services',
      descriptionEn: 'Specialized travel services to Macedonia, Greece, and the Balkans. Group tours, individual packages, and visa assistance.',
      descriptionMk: 'Специјализирани туристички услуги за Македонија, Грција и Балканот.',
      address: '88 Liverpool Street',
      suburb: 'Sydney',
      state: 'NSW',
      phone: '+61 2 9000 4444',
      email: 'travel@ohridtravel.com.au',
      website: 'https://ohridtravel.com.au',
      imageUrl: 'https://images.unsplash.com/photo-1469854523086-cc02fe5d8800?w=800',
      rating: 4.3,
      reviewCount: 67,
    ),
    Business(
      businessId: 'bus5',
      nameEn: 'Star Meats Butchery',
      nameMk: 'Стар Месо Касапница',
      category: 'Butcher',
      descriptionEn: 'Premium quality meats, smallgoods, and traditional Macedonian sausages. Family owned since 1985.',
      descriptionMk: 'Премиум квалитетно месо и традиционални македонски колбаси.',
      address: '67 High Street',
      suburb: 'Preston',
      state: 'VIC',
      phone: '+61 3 9000 5555',
      email: 'info@starmeats.com.au',
      website: '',
      imageUrl: 'https://images.unsplash.com/photo-1607623814075-e51df1bdc82f?w=800',
      rating: 4.8,
      reviewCount: 89,
    ),
    Business(
      businessId: 'bus6',
      nameEn: 'Bitola Auto Repairs',
      nameMk: 'Битола Авто Поправки',
      category: 'Services',
      descriptionEn: 'Full service auto mechanic. European car specialist. Honest, reliable service at fair prices.',
      descriptionMk: 'Целосен сервис за автомобили. Специјалист за европски автомобили.',
      address: '155 Barry Road',
      suburb: 'Campbellfield',
      state: 'VIC',
      phone: '+61 3 9000 6666',
      email: 'service@bitolauto.com.au',
      website: '',
      imageUrl: 'https://images.unsplash.com/photo-1619642751034-765dfdf7c58e?w=800',
      rating: 4.6,
      reviewCount: 35,
    ),
  ];

  // ============== ORGANISATIONS ==============
  static List<Organisation> organisations = [
    Organisation(
      organisationId: 'org1',
      nameEn: 'Macedonian Orthodox Church St. Petka',
      nameMk: 'Македонска Православна Црква Св. Петка',
      type: 'Church',
      descriptionEn: 'Serving the spiritual needs of the Macedonian community in Melbourne since 1962. Regular Sunday services, baptisms, weddings, and community events.',
      descriptionMk: 'Служи на духовните потреби на македонската заедница во Мелбурн од 1962 година.',
      phone: '+61 3 9000 7777',
      email: 'church@stpetka.org.au',
      website: 'https://stpetka.org.au',
      address: '340 Darebin Road',
      suburb: 'Thornbury',
      state: 'VIC',
      imageUrl: 'https://images.unsplash.com/photo-1548625149-fc4a29cf7092?w=800',
      president: 'Fr. Stefan Nikolovski',
      secretary: 'Maria Petrovska',
      founded: '1962',
      membershipInfo: 'Open to all Macedonian Orthodox faithful.',
    ),
    Organisation(
      organisationId: 'org2',
      nameEn: 'Macedonian Cultural Association of Sydney',
      nameMk: 'Македонско Културно Здружение на Сиднеј',
      type: 'Association',
      descriptionEn: 'Promoting Macedonian culture, language, and traditions in the greater Sydney area through events, classes, and cultural programs.',
      descriptionMk: 'Промовирање на македонската култура, јазик и традиции во Сиднеј.',
      phone: '+61 2 9000 8888',
      email: 'info@mcasydney.org.au',
      website: 'https://mcasydney.org.au',
      address: '55 Chapel Road',
      suburb: 'Bankstown',
      state: 'NSW',
      imageUrl: 'https://images.unsplash.com/photo-1523580494863-6f3031224c94?w=800',
      president: 'Dragan Jankulovski',
      secretary: 'Elena Dimitrova',
      founded: '1978',
      membershipInfo: 'Annual membership: \$50 individual, \$80 family.',
    ),
    Organisation(
      organisationId: 'org3',
      nameEn: 'Makedonka Dance Ensemble',
      nameMk: 'Танцов Ансамбл Македонка',
      type: 'Dance Group',
      descriptionEn: 'Traditional Macedonian folk dance ensemble performing at community events and festivals across Australia.',
      descriptionMk: 'Традиционален македонски фолклорен танцов ансамбл.',
      phone: '+61 3 9000 9999',
      email: 'dance@makedonka.org.au',
      website: '',
      address: '100 Station Street',
      suburb: 'Fairfield',
      state: 'VIC',
      imageUrl: 'https://images.unsplash.com/photo-1504609773096-104ff2c73ba4?w=800',
      president: 'Natasha Stojanovic',
      secretary: 'Ana Trajkovska',
      founded: '1990',
      membershipInfo: 'Rehearsals every Saturday. Contact for details.',
    ),
  ];

  // ============== EVENTS ==============
  static List<Event> events = [
    Event(
      eventId: 'e1',
      titleEn: 'Macedonian Heritage Festival 2026',
      titleMk: 'Фестивал на Македонско Наследство 2026',
      descriptionEn: 'Join us for our annual heritage festival celebrating Macedonian culture, food, music, and traditions. Live performances, traditional food stalls, folk dancing, and activities for the whole family.\n\nFeaturing performances by renowned Macedonian artists and local community ensembles. Food vendors will serve favorites including tavche gravche, ajvar, grilled meats, and traditional pastries.',
      descriptionMk: 'Придружете ни се на нашиот годишен фестивал на наследство кој ја слави македонската култура, храна, музика и традиции.',
      startDate: DateTime(2026, 5, 15, 10, 0),
      endDate: DateTime(2026, 5, 15, 22, 0),
      venue: 'Federation Square',
      venueAddress: 'Federation Square, Melbourne VIC 3000',
      organiserName: 'Macedonian Community of Australia Inc.',
      ticketUrl: 'https://macedoniancommunity.org.au/festival',
      imageUrl: 'https://images.unsplash.com/photo-1533174072545-7a4b6ad7a6c3?w=800',
      category: 'festival',
    ),
    Event(
      eventId: 'e2',
      titleEn: 'Easter Sunday Celebration',
      titleMk: 'Прослава на Велигденска Недела',
      descriptionEn: 'Orthodox Easter Sunday celebration at St. Petka Church. Morning liturgy followed by a community BBQ and egg cracking competition.',
      descriptionMk: 'Прослава на Велигденска Недела во Црквата Св. Петка.',
      startDate: DateTime(2026, 4, 19, 7, 0),
      endDate: DateTime(2026, 4, 19, 15, 0),
      venue: 'St. Petka Church',
      venueAddress: '340 Darebin Road, Thornbury VIC 3071',
      organiserName: 'Macedonian Orthodox Church St. Petka',
      ticketUrl: '',
      imageUrl: 'https://images.unsplash.com/photo-1521967906867-14ec9d64bee8?w=800',
      category: 'religious',
    ),
    Event(
      eventId: 'e3',
      titleEn: 'Macedonian Film Night',
      titleMk: 'Македонска Филмска Вечер',
      descriptionEn: 'Screening of award-winning Macedonian films with English subtitles. Discussion panel after each film.',
      descriptionMk: 'Проекција на наградени македонски филмови со англиски титлови.',
      startDate: DateTime(2026, 4, 10, 18, 30),
      endDate: DateTime(2026, 4, 10, 22, 0),
      venue: 'Macedonian Community Centre',
      venueAddress: '45 Community Drive, Thomastown VIC 3074',
      organiserName: 'MCA Cultural Committee',
      ticketUrl: '',
      imageUrl: 'https://images.unsplash.com/photo-1489599849927-2ee91cede3ba?w=800',
      category: 'community',
    ),
    Event(
      eventId: 'e4',
      titleEn: 'Youth Soccer Tournament',
      titleMk: 'Младински Фудбалски Турнир',
      descriptionEn: 'Annual youth soccer tournament for Macedonian community teams across Victoria. Age groups U8 to U16.',
      descriptionMk: 'Годишен младински фудбалски турнир за тимови на македонската заедница.',
      startDate: DateTime(2026, 6, 7, 9, 0),
      endDate: DateTime(2026, 6, 7, 17, 0),
      venue: 'Epping Recreation Reserve',
      venueAddress: 'Epping Recreation Reserve, Epping VIC 3076',
      organiserName: 'MCA Sports Committee',
      ticketUrl: '',
      imageUrl: 'https://images.unsplash.com/photo-1551958219-acbc608c6377?w=800',
      category: 'community',
    ),
    Event(
      eventId: 'e5',
      titleEn: 'Ilinden Celebration Dinner',
      titleMk: 'Илинденска Свечена Вечера',
      descriptionEn: 'Annual Ilinden celebration dinner commemorating the historic Ilinden uprising. Live music, traditional performances, and a three-course Macedonian dinner.',
      descriptionMk: 'Годишна Илинденска свечена вечера за комеморација на историското Илинденско востание.',
      startDate: DateTime(2026, 8, 2, 18, 0),
      endDate: DateTime(2026, 8, 2, 23, 0),
      venue: 'Grand Hyatt Melbourne',
      venueAddress: '123 Collins Street, Melbourne VIC 3000',
      organiserName: 'Macedonian Community of Australia Inc.',
      ticketUrl: 'https://macedoniancommunity.org.au/ilinden',
      imageUrl: 'https://images.unsplash.com/photo-1519167758481-83f550bb49b3?w=800',
      category: 'festival',
    ),
  ];

  // ============== RECIPES ==============
  static List<Recipe> recipes = [
    Recipe(
      recipeId: 'r1',
      titleEn: 'Tavče Gravče (Baked Beans)',
      titleMk: 'Тавче Гравче',
      category: 'Main Dish',
      ingredientsEn: ['500g white beans', '2 onions, diced', '2 tbsp paprika', '3 tbsp sunflower oil', '1 tsp salt', '1 dried chili pepper', 'Water as needed'],
      ingredientsMk: ['500г бел грав', '2 кромиди, исечени', '2 лажици алева пиперка', '3 лажици сончогледово масло', '1 лажичка сол', '1 сува лута пиперка', 'Вода по потреба'],
      instructionsEn: ['Soak beans overnight in cold water.', 'Boil beans until tender, about 1 hour.', 'Sauté onions in oil until golden.', 'Add paprika and chili, stir briefly.', 'Combine beans, onion mixture in clay pot.', 'Add enough bean water to cover.', 'Bake at 200°C for 40-50 minutes until top is golden.'],
      instructionsMk: ['Натопете го гравот преку ноќ во ладна вода.', 'Варете го гравот додека не омекне, околу 1 час.', 'Пржете ги кромидите во масло додека не позлатат.', 'Додадете пиперка и лута пиперка, промешајте.', 'Комбинирајте го гравот со мешавината од кромид во глинен сад.', 'Додадете доволно вода од гравот да се покрие.', 'Печете на 200°C за 40-50 минути додека горниот дел не позлати.'],
      prepTime: 90,
      difficulty: 'Easy',
      imageUrl: 'https://images.unsplash.com/photo-1585937421612-70a008356fbe?w=800',
    ),
    Recipe(
      recipeId: 'r2',
      titleEn: 'Ajvar (Pepper Relish)',
      titleMk: 'Ајвар',
      category: 'Appetizer',
      ingredientsEn: ['3kg red bell peppers', '500g eggplant', '200ml sunflower oil', '3 cloves garlic', '1 tbsp vinegar', 'Salt to taste'],
      ingredientsMk: ['3кг црвени пиперки', '500г модар патлиџан', '200мл сончогледово масло', '3 чешниња лук', '1 лажица оцет', 'Сол по вкус'],
      instructionsEn: ['Roast peppers and eggplant until charred.', 'Peel and drain overnight.', 'Chop finely or blend coarsely.', 'Cook slowly in oil for 2-3 hours, stirring frequently.', 'Add garlic, vinegar, and salt.', 'Jar while hot and seal.'],
      instructionsMk: ['Испечете ги пиперките и патлиџанот додека не потемнат.', 'Излупете ги и оставете да се исцедат преку ноќ.', 'Исечете ситно или мелете грубо.', 'Гответе полека во масло за 2-3 часа, мешајќи често.', 'Додадете лук, оцет и сол.', 'Ставете во тегли додека е топло и затворете.'],
      prepTime: 240,
      difficulty: 'Medium',
      imageUrl: 'https://images.unsplash.com/photo-1563379926898-05f4575a45d8?w=800',
    ),
    Recipe(
      recipeId: 'r3',
      titleEn: 'Zelnik (Cheese & Leek Pie)',
      titleMk: 'Зелник',
      category: 'Pastry',
      ingredientsEn: ['500g filo pastry', '300g feta cheese, crumbled', '2 large leeks, chopped', '3 eggs', '200ml yogurt', '100ml sunflower oil', 'Salt and pepper'],
      ingredientsMk: ['500г коричка за зелник', '300г сирење, изронето', '2 големи праси, исечени', '3 јајца', '200мл јогурт', '100мл сончогледово масло', 'Сол и бибер'],
      instructionsEn: ['Mix cheese, leeks, eggs, and yogurt.', 'Layer filo sheets in oiled baking pan.', 'Spread filling between layers.', 'Brush top with oil and egg wash.', 'Bake at 180°C for 35-40 minutes.', 'Let rest 10 minutes before cutting.'],
      instructionsMk: ['Измешајте сирење, праси, јајца и јогурт.', 'Наредете ги корите во подмачкан плех.', 'Распоредете го филот меѓу слоевите.', 'Премачкајте го врвот со масло и јајце.', 'Печете на 180°C за 35-40 минути.', 'Оставете да се олади 10 минути пред сечење.'],
      prepTime: 60,
      difficulty: 'Medium',
      imageUrl: 'https://images.unsplash.com/photo-1604068549290-dea0e4a305ca?w=800',
    ),
    Recipe(
      recipeId: 'r4',
      titleEn: 'Shopska Salad',
      titleMk: 'Шопска Салата',
      category: 'Salad',
      ingredientsEn: ['4 tomatoes', '2 cucumbers', '1 onion', '2 green peppers', '200g white cheese', 'Olive oil', 'Salt'],
      ingredientsMk: ['4 домати', '2 краставици', '1 кромид', '2 зелени пиперки', '200г бело сирење', 'Маслиново масло', 'Сол'],
      instructionsEn: ['Dice tomatoes, cucumbers, onion, and peppers.', 'Arrange in a serving bowl.', 'Grate cheese generously on top.', 'Drizzle with olive oil.', 'Season with salt.'],
      instructionsMk: ['Исечете ги доматите, краставиците, кромидот и пиперките.', 'Наредете во чинија за сервирање.', 'Настружете сирење одгоре.', 'Полејте со маслиново масло.', 'Зачинете со сол.'],
      prepTime: 15,
      difficulty: 'Easy',
      imageUrl: 'https://images.unsplash.com/photo-1540420773420-3366772f4999?w=800',
    ),
  ];

  // ============== RADIO STATIONS ==============
  static List<RadioStation> radioStations = [
    RadioStation(stationId: 'rs1', name: 'Antenna 5', streamUrl: 'https://www.antenna5.com.mk/', logoUrl: 'https://images.unsplash.com/photo-1614680376593-902f74cf0d41?w=200', region: 'National', genre: 'Pop'),
    RadioStation(stationId: 'rs2', name: 'Kanal 77', streamUrl: 'https://kanal77.mk/', logoUrl: 'https://images.unsplash.com/photo-1614680376408-81e91ffe3db7?w=200', region: 'Skopje', genre: 'Mixed'),
    RadioStation(stationId: 'rs3', name: 'Radio Bitola', streamUrl: 'https://stream.zeno.fm/0a1fxr69dm0uv', logoUrl: 'https://images.unsplash.com/photo-1571330735066-03aaa9429d89?w=200', region: 'Bitola', genre: 'Folk'),
    RadioStation(stationId: 'rs4', name: 'MRT Radio 1', streamUrl: 'https://www.mrt.com.mk/', logoUrl: 'https://images.unsplash.com/photo-1590602847861-f357a9332bbc?w=200', region: 'National', genre: 'News'),
    RadioStation(stationId: 'rs5', name: 'City Radio Skopje', streamUrl: 'https://cityradio.com.mk/', logoUrl: 'https://images.unsplash.com/photo-1478737270239-2f02b77fc618?w=200', region: 'Ohrid', genre: 'Folk'),
    RadioStation(stationId: 'rs6', name: 'Metropolis Radio', streamUrl: 'https://metropolisradio.com.mk/', logoUrl: 'https://images.unsplash.com/photo-1493225457124-a3eb161ffa5f?w=200', region: 'Skopje', genre: 'Pop'),
  ];

  // ============== TV CHANNELS ==============
  static List<TvChannel> tvChannels = [
    TvChannel(channelId: 'tv1', name: 'MRT 1', descriptionEn: 'Macedonian National TV - Channel 1', descriptionMk: 'Македонска Радио Телевизија - Канал 1', streamUrl: 'https://vipottbpkstream.vip.hr/Content/onevip-hls/Live/Channel(MRT_1)/index.m3u8', streamType: 'hls', websiteUrl: 'https://www.mrt.com.mk/', logoUrl: 'https://upload.wikimedia.org/wikipedia/commons/thumb/5/5e/MRT_logo.svg/200px-MRT_logo.svg.png'),
    TvChannel(channelId: 'tv2', name: 'Sitel TV', descriptionEn: 'Sitel Television - Most watched TV', descriptionMk: 'Сител Телевизија', streamUrl: 'https://vipottbpkstream.vip.hr/Content/onevip-hls/Live/Channel(Sitel)/index.m3u8', streamType: 'hls', websiteUrl: 'https://sitel.com.mk/', logoUrl: 'https://upload.wikimedia.org/wikipedia/commons/thumb/0/0e/Sitel_TV_logo.svg/200px-Sitel_TV_logo.svg.png'),
    TvChannel(channelId: 'tv3', name: 'Kanal 5', descriptionEn: 'Kanal 5 Television', descriptionMk: 'Канал 5 Телевизија', streamUrl: 'https://vipottbpkstream.vip.hr/Content/onevip-hls/Live/Channel(Kanal_5)/index.m3u8', streamType: 'hls', websiteUrl: 'https://kanal5.com.mk/', logoUrl: 'https://upload.wikimedia.org/wikipedia/commons/thumb/3/3c/Kanal5_mk_logo.svg/200px-Kanal5_mk_logo.svg.png'),
    TvChannel(channelId: 'tv4', name: 'Telma TV', descriptionEn: 'Telma Television', descriptionMk: 'Телма Телевизија', streamUrl: 'https://vipottbpkstream.vip.hr/Content/onevip-hls/Live/Channel(Telma)/index.m3u8', streamType: 'hls', websiteUrl: 'https://telma.com.mk/', logoUrl: 'https://upload.wikimedia.org/wikipedia/commons/thumb/4/4a/Telma_TV_logo.svg/200px-Telma_TV_logo.svg.png'),
    TvChannel(channelId: 'tv5', name: 'Alfa TV', descriptionEn: 'Alfa Television', descriptionMk: 'Алфа Телевизија', streamUrl: 'https://vipottbpkstream.vip.hr/Content/onevip-hls/Live/Channel(Alfa)/index.m3u8', streamType: 'hls', websiteUrl: 'https://alfa.mk/', logoUrl: 'https://upload.wikimedia.org/wikipedia/commons/thumb/5/5a/Alfa_TV_logo.svg/200px-Alfa_TV_logo.svg.png'),
    TvChannel(channelId: 'tv6', name: 'Alsat-M', descriptionEn: 'Alsat-M Television', descriptionMk: 'Алсат-М Телевизија', streamUrl: 'https://vipottbpkstream.vip.hr/Content/onevip-hls/Live/Channel(Alsat_M)/index.m3u8', streamType: 'hls', websiteUrl: 'https://alsat.mk/', logoUrl: 'https://upload.wikimedia.org/wikipedia/en/thumb/6/63/Alsat-M_logo.svg/200px-Alsat-M_logo.svg.png'),
    TvChannel(channelId: 'tv7', name: 'Nasa TV', descriptionEn: 'Nasa Television', descriptionMk: 'Наша Телевизија', streamUrl: 'https://stream.nasatv.com.mk/hls/nasatv_live.m3u8', streamType: 'hls', websiteUrl: 'https://nasatv.com.mk/', logoUrl: 'https://upload.wikimedia.org/wikipedia/commons/thumb/b/ba/Nasa_TV_logo.svg/200px-Nasa_TV_logo.svg.png'),
    TvChannel(channelId: 'tv8', name: 'Sky Folk TV', descriptionEn: 'Sky Folk Music Television', descriptionMk: 'Скај Фолк Музичка Телевизија', streamUrl: 'https://skyfolk.mk/live.m3u8', streamType: 'hls', websiteUrl: 'https://skyfolk.mk/', logoUrl: 'https://upload.wikimedia.org/wikipedia/en/thumb/0/0c/Sky_Folk_TV_logo.png/200px-Sky_Folk_TV_logo.png'),
    TvChannel(channelId: 'tv9', name: 'Folk TV', descriptionEn: 'Folk Music Television', descriptionMk: 'Фолк Музичка Телевизија', streamUrl: 'https://stream.nasatv.com.mk/folktv/hls/folktv_live.m3u8', streamType: 'hls', websiteUrl: '', logoUrl: 'https://images.unsplash.com/photo-1511671782779-c97d3d27a1d4?w=200'),
    TvChannel(channelId: 'tv10', name: 'MRT 2', descriptionEn: 'Macedonian National TV - Channel 2', descriptionMk: 'МРТ 2', streamUrl: 'https://vipottbpkstream.vip.hr/Content/onevip-hls/Live/Channel(MRT_2)/index.m3u8', streamType: 'hls', websiteUrl: 'https://www.mrt.com.mk/', logoUrl: 'https://upload.wikimedia.org/wikipedia/commons/thumb/5/5e/MRT_logo.svg/200px-MRT_logo.svg.png'),
  ];

  // ============== TOURISM PLACES ==============
  static List<TourismPlace> tourismPlaces = [
    TourismPlace(placeId: 'tp1', nameEn: 'Lake Ohrid', nameMk: 'Охридско Езеро', region: 'Ohrid', category: 'Lakes', descriptionEn: 'One of Europe\'s oldest and deepest lakes, UNESCO World Heritage Site. Crystal clear waters, stunning sunsets, and rich biodiversity.', descriptionMk: 'Едно од најстарите и најдлабоките езера во Европа, дел од светското наследство на УНЕСКО.', imageUrl: 'https://images.unsplash.com/photo-1596394516093-501ba68a0ba6?w=800'),
    TourismPlace(placeId: 'tp2', nameEn: 'Matka Canyon', nameMk: 'Кањон Матка', region: 'Skopje', category: 'National Parks', descriptionEn: 'Stunning canyon just 15km from Skopje. Perfect for kayaking, hiking, and cave exploration.', descriptionMk: 'Прекрасен кањон само 15км од Скопје.', imageUrl: 'https://images.unsplash.com/photo-1506905925346-21bda4d32df4?w=800'),
    TourismPlace(placeId: 'tp3', nameEn: 'Bitola Old Bazaar', nameMk: 'Битолска Стара Чаршија', region: 'Bitola', category: 'Historic Sites', descriptionEn: 'Historic marketplace and cultural heart of Bitola, known as the "City of Consuls".', descriptionMk: 'Историски пазар и културно срце на Битола, познат како „Град на конзулите".', imageUrl: 'https://images.unsplash.com/photo-1555990538-1a0d2d180740?w=800'),
    TourismPlace(placeId: 'tp4', nameEn: 'St. Jovan Bigorski Monastery', nameMk: 'Манастир Св. Јован Бигорски', region: 'Debar', category: 'Monasteries', descriptionEn: 'One of the most important monasteries in Macedonia, famous for its intricate wood-carved iconostasis.', descriptionMk: 'Еден од најважните манастири во Македонија.', imageUrl: 'https://images.unsplash.com/photo-1548625149-fc4a29cf7092?w=800'),
    TourismPlace(placeId: 'tp5', nameEn: 'Pelister National Park', nameMk: 'Национален Парк Пелистер', region: 'Bitola', category: 'National Parks', descriptionEn: 'Macedonia\'s oldest national park featuring molika pine forests, glacial lakes, and hiking trails.', descriptionMk: 'Најстариот национален парк во Македонија.', imageUrl: 'https://images.unsplash.com/photo-1441974231531-c6227db76b6e?w=800'),
    TourismPlace(placeId: 'tp6', nameEn: 'Skopje Fortress (Kale)', nameMk: 'Скопско Кале', region: 'Skopje', category: 'Historic Sites', descriptionEn: 'Ancient fortress overlooking Skopje, offering panoramic views of the city and the Vardar River.', descriptionMk: 'Античка тврдина со поглед на Скопје.', imageUrl: 'https://images.unsplash.com/photo-1599946347371-68eb71b16afc?w=800'),
  ];

  // ============== ORTHODOX CALENDAR ==============
  static Map<String, OrthodoxDay> orthodoxCalendar = {
    '2026-03-27': OrthodoxDay(
      dateKey: '2026-03-27',
      julianDate: '2026-03-14',
      saintsEn: ['St. Benedict of Nursia', 'Venerable Alexis the Man of God'],
      saintsMk: ['Св. Бенедикт Нурсиски', 'Преподобен Алексиј Божји Човек'],
      feastType: 'regular',
      fastingRule: 'oil_allowed',
      readings: ['Genesis 13:12-18', 'Proverbs 14:15-26'],
    ),
    '2026-03-28': OrthodoxDay(
      dateKey: '2026-03-28',
      julianDate: '2026-03-15',
      saintsEn: ['Hieromartyr Alexander of Side', 'Martyr Agapius'],
      saintsMk: ['Свештеномаченик Александар Сидски', 'Маченик Агапиј'],
      feastType: 'regular',
      fastingRule: 'strict',
      readings: ['Genesis 14:14-20', 'Proverbs 15:7-19'],
    ),
    '2026-03-29': OrthodoxDay(
      dateKey: '2026-03-29',
      julianDate: '2026-03-16',
      saintsEn: ['Martyr Sabinus of Egypt'],
      saintsMk: ['Маченик Савин Египетски'],
      feastType: 'regular',
      fastingRule: 'fish',
      readings: ['Hebrews 6:9-12', 'Mark 7:31-37'],
    ),
    '2026-04-19': OrthodoxDay(
      dateKey: '2026-04-19',
      julianDate: '2026-04-06',
      saintsEn: ['PASCHA - The Resurrection of Our Lord Jesus Christ'],
      saintsMk: ['ВЕЛИГДЕН - Воскресение Христово'],
      feastType: 'great_feast',
      fastingRule: 'none',
      readings: ['Acts 1:1-8', 'John 1:1-17'],
    ),
    '2026-08-15': OrthodoxDay(
      dateKey: '2026-08-15',
      julianDate: '2026-08-02',
      saintsEn: ['Dormition of the Most Holy Theotokos'],
      saintsMk: ['Успение на Пресвета Богородица (Голема Богородица)'],
      feastType: 'great_feast',
      fastingRule: 'none',
      readings: ['Philippians 2:5-11', 'Luke 10:38-42; 11:27-28'],
    ),
  };

  static OrthodoxDay getTodayCalendar() {
    final today = DateTime.now();
    final key = '${today.year}-${today.month.toString().padLeft(2, '0')}-${today.day.toString().padLeft(2, '0')}';
    return orthodoxCalendar[key] ?? OrthodoxDay(
      dateKey: key,
      julianDate: '',
      saintsEn: ['Saint of the Day'],
      saintsMk: ['Светец на денот'],
      feastType: 'regular',
      fastingRule: 'none',
    );
  }

  // ============== WEATHER DATA ==============
  static WeatherData getWeather(String cityKey) {
    return WeatherData(
      cityKey: cityKey,
      currentTemp: 18,
      condition: 'Partly Cloudy',
      icon: '⛅',
      hourlyForecast: List.generate(24, (i) => HourlyForecast(
        time: '${i.toString().padLeft(2, '0')}:00',
        temp: 14 + (i < 12 ? i * 0.5 : (24 - i) * 0.5),
        icon: i > 6 && i < 18 ? '☀️' : '🌙',
      )),
      dailyForecast: [
        DailyForecast(day: 'Mon', high: 22, low: 12, icon: '☀️', condition: 'Sunny'),
        DailyForecast(day: 'Tue', high: 20, low: 11, icon: '⛅', condition: 'Partly Cloudy'),
        DailyForecast(day: 'Wed', high: 18, low: 10, icon: '🌧️', condition: 'Rainy'),
        DailyForecast(day: 'Thu', high: 19, low: 9, icon: '⛅', condition: 'Partly Cloudy'),
        DailyForecast(day: 'Fri', high: 21, low: 11, icon: '☀️', condition: 'Sunny'),
      ],
    );
  }
}
